//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8NJW4MQV67WYP431GIDV2UP895M4JFG8M3,Y97RJDVH8ANJDPZMX9HPMQ9ABEZWIBXCSX,NSW1V9PTSY6FCCRQZD2S3C4DGVVE1DGYD6,V98WJIEX72P667IFC8FWRTJU7HJXMJ5Z2N,8AWFUCTBEUY764QJFWYYG1IP2Z2BDPA62Z.
        /// </summary>
        internal static string BscScanAPIKey {
            get {
                return ResourceManager.GetString("BscScanAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip,anonymityLevel,asn,country,isp,latency,org,port,protocols,responseTime,speed,updated_at
        ///&quot;209.33.249.165&quot;,&quot;elite&quot;,&quot;AS11071&quot;,&quot;US&quot;,&quot;InfoWest, Inc.&quot;,&quot;23&quot;,&quot;InfoWest, Inc&quot;,&quot;5678&quot;,&quot;socks4&quot;,&quot;34&quot;,&quot;5001&quot;,&quot;2021-08-18T20:41:09.849Z&quot;
        ///&quot;190.226.241.67&quot;,&quot;elite&quot;,&quot;AS264691&quot;,&quot;AR&quot;,&quot;Servicoop S.A.&quot;,&quot;201&quot;,&quot;Servicoop S.A&quot;,&quot;3629&quot;,&quot;socks4&quot;,&quot;36&quot;,&quot;5003&quot;,&quot;2021-08-18T20:41:08.248Z&quot;
        ///&quot;178.161.242.252&quot;,&quot;elite&quot;,&quot;AS12768&quot;,&quot;RU&quot;,&quot;OOO Saturn-R Internet&quot;,&quot;187&quot;,&quot;OOO Saturn-R Internet&quot;,&quot;5678&quot;,&quot;socks4&quot;,&quot;34&quot;,&quot;N/A&quot;,&quot;2021-08-18T20:41:08.725Z&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyList {
            get {
                return ResourceManager.GetString("ProxyList", resourceCulture);
            }
        }
    }
}
